application: previousnext/lamp

test: &test
  steps:
    - composer install --prefer-dist --dev
    - bundle install --path vendor/bundle
    - npm install
    - bin/phing build -Dapp.password=$PASSWORD
    - bin/phing gulp:build
    - bin/phing styleguide:link
    - bin/phing test
    - node_modules/.bin/gulp lint:js-with-fail
    - node_modules/.bin/gulp lint:sass-with-fail
    - mkdir -p app/sites/default/files/tmp
    - mkdir -p app/sites/default/private

test_pr:
  <<: *test

test_head:
  <<: *test
