application: previousnext/lamp

channel: "#agov-8"

test: &test
  steps:
    - composer install --prefer-dist --dev
    - bundle install --path vendor/bundle
    - npm install
    - bin/phing build:dev -Dapp.password=$PASSWORD
    - bin/phing gulp:build
    - bin/phing styleguide:link
    - bin/phing test
    - node_modules/.bin/gulp lint:js-with-fail
    - node_modules/.bin/gulp lint:sass-with-fail
    - mkdir -p app/sites/default/files/tmp
    - mkdir -p app/sites/default/private

test_pr:
  <<: *test

test_head:
  <<: *test

deploy_8_1:
  steps:
    - npm install
    # Compiled CSS.
    - gulp
    - git add -f agov/themes/agov/agov_whitlam/css
    - git add .
    - git commit -m 'Compiled CSS.'
    # Filter out the commits only in the 'agov' folder.
    - git filter-branch --prune-empty --subdirectory-filter agov 8.x-1.x
    # Clean up the state of the folder.
    - git checkout 8.x-1.x
    - git add .
    - git reset --hard
    # Add drupal.org as a remote.
    - git remote add dorg git@github.com:previousnext/agov.git
    - git fetch dorg
    # Add the existing build commits into the current branch.
    - git rebase dorg/jenkins-test
    # Push the new commits and build commit to the remote.
    - git push dorg jenkins-test
