application: previousnext/lamp

test: &test
  steps:
    - composer install --prefer-dist --dev
    - bundle install --path vendor/bundle
    - npm install
    - bin/phing build:dev -Dapp.password=$PASSWORD
    - bin/phing gulp:build
    - bin/phing styleguide:link
    - bin/phing test
    - node_modules/.bin/gulp lint:js-with-fail
    - node_modules/.bin/gulp lint:sass-with-fail
    - mkdir -p app/sites/default/files/tmp
    - mkdir -p app/sites/default/private

test_pr:
  <<: *test

test_head:
  <<: *test

deploy_8_1:
  - git fetch && git checkout -b 8.x-1.x origin/8.x-1.x
  - git filter-branch --prune-empty --subdirectory-filter agov 8.x-1.x
  - git checkout 8.x-1.x
  - git add .
  - git reset --hard
  - git status
  - git log | head -n25
  - ls -lah
  - git remote add dorg git@github.com:previousnext/agov.git
  - git checkout -b jenkins-test
  - git push dorg jenkins-test
