application: previousnext/lamp

test: &test
  steps:
    - composer install --prefer-dist --dev
    - bin/phing build -Dapp.password=$PASSWORD
    - mkdir -p app/sites/default/files/tmp app/sites/default/private
    - bin/phing test 

test_pr:
  <<: *test

test_head:
  <<: *test

