language: php

php:
  - 5.3
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  fast_finish: true

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # Install global composer dependencies.
  - composer install --prefer-dist --dev

  # Prepare build and install composer dependencies
  - cp build.travis.properties build.properties

  # Install Apache so we can get close running a production style environment.
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f misc/vhost.conf /etc/apache2/sites-enabled/000-default
  - sudo sed -e "s?%BUILD_DIR%?$(pwd)/app?g" --in-place /etc/apache2/sites-enabled/000-default
  - sudo service apache2 restart

  # Disable sendmail.
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - bin/phing build

script:
  - bin/phing test

notifications:
  email:
    recipients:
      - agov-devs@previousnext.com.au
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#agov"
    on_success: always
    on_failure: always
