web:
  image: previousnext/agov:8.0.1
  links:
   - db
  ports:
   - "80:80"
  environment:
    DRUPAL_PROFILE:         agov
    DRUPAL_DIR_CONFIG_SYNC: sites/default/files/foo
    DRUPAL_HASH_SALT:       asdsafasdfasdf
    DRUPAL_DB_NAME:         drupal
    DRUPAL_DB_USER:         drupal
    DRUPAL_DB_PASS:         password
    DRUPAL_DB_HOST:         db
db:
  image: mysql
  environment:
    # https://docs.docker.com/compose/yml/#environment
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER:          drupal 
    MYSQL_PASSWORD:      password
    MYSQL_DATABASE:      drupal
